services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-backend:
    depends_on:
      - mysqldb
    image: mariem5/school-devops:1.0.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/school_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
  app-school-frontend:
    image: mouradhassini/student-front-image:1.0.0
    restart: on-failure
    ports:
      - 8085:85
    depends_on:
      - app-backend 
    
volumes:
  db :
